#!/usr/bin/env bash
getscs(){
 TEST=$(kubectl get sc 2>&1)
  if [ $? -eq 0 ];then
    rez=$(echo "$TEST" | tail -n +2 | cut -d" " -f1)
    echo "$rez"
  fi
}
getvscs(){
  TEST=$(kubectl get volumesnapshotclass 2>&1)
  if [ $? -eq 0 ];then
    rez=$(echo "$TEST" | tail -n +2 | cut -d" " -f1)
    echo "$rez"
  fi
}
: ${PROG:=$(basename ${BASH_SOURCE})}

_cli_bash_autocomplete() {
  if [[ "${COMP_WORDS[0]}" != "source" ]]; then
    local cur opts base
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    if [[ "$cur" == "-"* ]]; then
      opts=$( ${COMP_WORDS[@]:0:$COMP_CWORD} ${cur} --generate-bash-completion )
    elif [[ ${COMP_WORDS[-2]} == "--sc" || ${COMP_WORDS[-2]} == "--storageclass" ]];then
      opts=$(getscs)
    elif [[ ${COMP_WORDS[-2]} == "--vsc" || ${COMP_WORDS[-2]} == "--volumeSnapshotClass" ]];then
      opts=$(getvscs)
    else
      opts=$( ${COMP_WORDS[@]:0:$COMP_CWORD} --generate-bash-completion )
    fi
    COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
    return 0
  fi
}


complete -o bashdefault -o default -o nospace -F _cli_bash_autocomplete $PROG
unset PROG