apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://localhost:8080
  name: mock-cluster
contexts:
- context:
    cluster: mock-cluster
    user: mock-user
  name: mock-context
current-context: mock-context
users:
- name: mock-user
  user:
    token: mock-token