// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dell/cert-csi/pkg/testcore/runner (interfaces: K8sClientInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	k8sclient "github.com/dell/cert-csi/pkg/k8sclient"
	gomock "github.com/golang/mock/gomock"
	rest "k8s.io/client-go/rest"
)

// MockK8sClientInterface is a mock of K8sClientInterface interface.
type MockK8sClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockK8sClientInterfaceMockRecorder
}

// MockK8sClientInterfaceMockRecorder is the mock recorder for MockK8sClientInterface.
type MockK8sClientInterfaceMockRecorder struct {
	mock *MockK8sClientInterface
}

// NewMockK8sClientInterface creates a new mock instance.
func NewMockK8sClientInterface(ctrl *gomock.Controller) *MockK8sClientInterface {
	mock := &MockK8sClientInterface{ctrl: ctrl}
	mock.recorder = &MockK8sClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockK8sClientInterface) EXPECT() *MockK8sClientInterfaceMockRecorder {
	return m.recorder
}

// GetConfig mocks base method.
func (m *MockK8sClientInterface) GetConfig(arg0 string) (*rest.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig", arg0)
	ret0, _ := ret[0].(*rest.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockK8sClientInterfaceMockRecorder) GetConfig(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockK8sClientInterface)(nil).GetConfig), arg0)
}

// NewKubeClient mocks base method.
func (m *MockK8sClientInterface) NewKubeClient(arg0 *rest.Config, arg1 int) (*k8sclient.KubeClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewKubeClient", arg0, arg1)
	ret0, _ := ret[0].(*k8sclient.KubeClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewKubeClient indicates an expected call of NewKubeClient.
func (mr *MockK8sClientInterfaceMockRecorder) NewKubeClient(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewKubeClient", reflect.TypeOf((*MockK8sClientInterface)(nil).NewKubeClient), arg0, arg1)
}