#
#
# Copyright © 2022-2023 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
  storageClassName: powerstore
---
apiVersion: v1
kind: Pod
metadata:
  generateName: test-pod
spec:
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: test-pvc
  containers:
    - name: test
      image: quay.io/centos/centos:latest
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: pv-storage
          mountPath: /data0
      command: ["/bin/bash"]
      args: ["-c", "trap 'exit 0' SIGTERM;while true; do sleep 1; done"]
