name: Common Workflows
on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

jobs:
  go_security_scan:
    name: Run gosec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Run gosec to check for security vulnerabilities
        uses: dell/common-github-actions/gosec-runner@main
        with:
          directories: "./..."
  common:
    name: Quality Checks
    uses: dell/common-github-actions/.github/workflows/go-common.yml@main
