name: Common Workflows
on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

jobs:
  code-check:
    name: Check Go formatting, linting, vetting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Run the formatter, linter, and vetter
        uses: dell/common-github-actions/go-code-formatter-linter-vetter@main
        with:
          directories: ./...
  go_security_scan:
    name: Run gosec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Run gosec to check for security vulnerabilities
        uses: dell/common-github-actions/gosec-runner@main
        with:
          directories: "./..."
  common:
    name: Quality Checks
    uses: dell/common-github-actions/.github/workflows/go-common.yml@main
