name: Common Workflows
on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: ["**"]
jobs:
  common:
    name: Quality Checks
    uses: dell/common-github-actions/.github/workflows/go-common.yml@main
